### ISSUE TITLE
I have python installed but i cant install the req

### ISSUE THREAD

**Issue by ReadingcookiesA** [bear102/betterQuill#1]
its giving me a error 
![image](https://github.com/bear102/betterQuill/assets/135073450/27054bcf-9944-4747-91cf-17a0f2823f31)

**Comment by ReadingcookiesA** [comment]
@bear102

**Comment by bear102** [comment]
@ReadingcookiesA 
Hola thats because you are inside python.

To fix it you should:
1. open your command prompt by typing cmd in the bar at the bottom of your screen and clicking on command prompt.
2. Go to the directory where you downloaded the files. Use the command cd. Example: cd C:\bear102\Downloads\betterQuill
3. run the command pip install -r requirements.txt

**Comment by ReadingcookiesA** [comment]
btw @bear102 does this work on microsoft edge???

**Comment by bear102** [comment]
well its designed to work on chrome. it uses chromedriver, a program built for google chrome.
